version: "3.7"

services: 
  database:
    image: postgres
    container_name: pgdb
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rents
    volumes:
      - pgdata:/data/postgres
    networks: 
      - rents
    # network_mode: host
  app:
    build: .
    container_name: tsprim
    ports: 
      - 3333:3333
    volumes:
      - .:/usr/app
    # network_mode: host
    networks: 
      - rents
    # links:
    #   - database
    # depends_on:
    #   - database

volumes: 
  pgdata:
    driver: local
networks:
  rents:
